name: nihonggo_apk
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/hiragana.jpg
    - assets/katakana.jpg
    - assets/kanji.png
    - assets/KeteranganWaktu.jpg
